<?php

namespace AppBundle\Repository;

/**
 * AttackTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttackTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
