<?php

namespace AppBundle\Repository;

/**
 * BuildingGropuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingGropuRepository extends \Doctrine\ORM\EntityRepository
{
}
