<?php

namespace AppBundle\Repository;

/**
 * BuildingCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
