<?php

namespace AppBundle\Repository;

/**
 * BuildingQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
