<?php

namespace AppBundle\Repository;

/**
 * CaravanQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaravanQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
