<?php

namespace AppBundle\Repository;

/**
 * ResearchQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResearchQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
