<?php

namespace AppBundle\Repository;

/**
 * ResearchRequiredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResearchRequiredRepository extends \Doctrine\ORM\EntityRepository
{
}
