<?php

namespace AppBundle\Repository;

/**
 * ResearchGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResearchGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
