<?php

namespace AppBundle\Repository;

/**
 * ResearchCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResearchCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
