<?php

namespace AppBundle\Repository;

/**
 * ResearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResearchRepository extends \Doctrine\ORM\EntityRepository
{
}
