<?php

namespace AppBundle\Repository;

/**
 * ResourceGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
