<?php

namespace AppBundle\Repository;

/**
 * TradeQueuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeQueuRepository extends \Doctrine\ORM\EntityRepository
{
}
