<?php

namespace AppBundle\Repository;

/**
 * TradeQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradeQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
