<?php

namespace AppBundle\Repository;

/**
 * TroopQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TroopQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
