<?php

namespace AppBundle\Repository;

/**
 * UnitAttackTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitAttackTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
