<?php

namespace AppBundle\Repository;

/**
 * UnitDefenseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitDefenseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
