<?php

namespace AppBundle\Repository;

/**
 * UnitGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
