<?php

namespace AppBundle\Repository;

/**
 * UnitCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
