<?php

namespace AppBundle\Repository;

/**
 * UnitDefenseTerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitDefenseTerrainRepository extends \Doctrine\ORM\EntityRepository
{
}
