<?php

namespace AppBundle\Repository;

/**
 * UnitQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
