admin_admin:
    resource: "@AdminAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

client_client:
    resource: "@ClientClientBundle/Controller/"
    type:     annotation
    prefix:   /client

front_front:
    resource: "@FrontFrontBundle/Controller/"
    type:     annotation
    prefix:   /

