security:

    providers:
        users_in_memory:
            memory:
                users:
                    client:
                        password: clientpass
                        roles: 'ROLE_CLIENT'
                    app:
                        password: apppass
                        roles: 'ROLE_APP'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: users_in_memory
            anonymous: ~
            logout_on_user_change: true
            http_basic: ~

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: '^/app', roles: ROLE_APP }
        - { path: '^/client', roles: ROLE_CLIENT }
