services:
#    admin_admin.example:
#        class: Admin\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

        Admin\AdminBundle\Service\FileUploader:
          arguments:
            $targetDirectory: '%files_directory%'
